---
kind: pipeline
name: Request code review
steps:
- commands:
  - echo "start send notification"
  - env
  - 'echo "This is triggered by a custom event cp:${custom_param} dcp: ${DRONE_CUSTOM_PARAM}
    dce: ${DRONE_CUSTOM_ENV}"'
  image: alpine
  name: Send notification
trigger:
  event:
  - custom
type: docker
---
kind: pipeline
name: Build for UAT stage
steps:
- commands:
  - composer install
  image: composer
  name: Install
trigger:
  branch:
  - uat
  event:
  - push
type: docker
---
kind: pipeline
name: Deploy to UAT stage
steps:
- commands:
  - echo "start build for UAT"
  image: alpine
  name: Build for UAT
trigger:
  event:
  - promote
  target:
  - UAT
type: docker
