---
kind: pipeline
name: start_drone
steps:
- commands:
  - echo start run drone
  image: alpine
  name: Start Run Drone
type: docker
---
kind: pipeline
name: build
steps:
- commands:
  - echo start build on PR labeled
  image: alpine
  name: Build
trigger:
  action:
  - opened
  - synchronize
  event:
  - pull_request
type: docker
